Repository databrickslabs/blueprint, pull requests merged in 2024-07, with the labels that each got.

#121 Fixed `WorkspacePath` support for python 3.11
  src/databricks/labs/blueprint/paths.py
Labels: bug

#123 Fix build workflow: verify/lint
  pyproject.toml
Labels: bug, dependencies

#125 Update `WorkspaceClient` to support globbing
  src/databricks/labs/blueprint/paths.py
  tests/unit/test_paths.py
Labels: enhancement

#122 Update `WorkspacePath` to support Python 3.12
  pyproject.toml
  src/databricks/labs/blueprint/paths.py
  tests/unit/test_paths.py
Labels: pr/do-not-merge

#127 Fix `.as_uri()` and `.absolute()` implementations for `WorkspacePath`
  src/databricks/labs/blueprint/paths.py
  tests/unit/test_paths.py
Labels: bug

#129 `WorkspacePath` fixes for the `.resolve()` implementation
  src/databricks/labs/blueprint/paths.py
  tests/unit/test_paths.py
Labels: bug

#130 `WorkspacePath`: Fix the .rename() and .replace() implementations to return the target path
  src/databricks/labs/blueprint/paths.py
  tests/unit/test_paths.py
Labels: bug

#132 Improved integration tests for `WorkspacePath`
  tests/integration/test_paths.py
Labels: internal

#131 Added `DBFSPath` as `os.PathLike` implementation
  src/databricks/labs/blueprint/paths.py
  tests/integration/test_paths.py
  tests/unit/test_paths.py
Labels: enhancement
